version: '3'

services:
  gender-api:
    build: .
    container_name: gender-api
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1  # Enables real-time logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"