services:
  gender-api:
    build: .
    container_name: gender-api
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1 # Enables real-time logging
      - PYTHONPATH=/app # Ensures modules can be found
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
