name: Sync to Hugging Face Space

on:
  push:
    branches: [main]  # change if your default branch is different
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - name: Push to Hugging Face Space
        run: |
          git remote add hf https://user:${HF_TOKEN}@huggingface.co/spaces/Midnightar/voice-gender-detection
          git push --force hf main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
