name: Upload model to Hugging Face

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push model files to Hugging Face Model repo
        run: |
          git lfs install
          git clone https://user:${HF_TOKEN}@huggingface.co/Midnightar/voice-gender-model hf-model
          cp path/to/your/model.pth hf-model/
          cd hf-model
          git lfs track "*.pth"
          git add .
          git commit -m "Add model from GitHub repo"
          git push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
